datamodule:
  name: CpClassifierDataModule
  config:
    dataset_dir: <path/to/dataset>
    batch_size: 256
    num_workers: 8
    labels:
      0: 0 # CP starts
      1: 1 # CP spares
      2: 2 # noise
