module:
  name: CpClassifier
  config:
    model:
      name: ResNetTimeSeriesClassifier
      config:
        encoder_params:
          encoding_size: 32
          base_filters: 16
          kernel_size: 64
          stride: 1
          groups: 1
          n_block: 2
          downsample_gap: 3
          increasefilter_gap: 1
          use_batch_norm: True
          use_inner_do: True
          inner_do_val: 0.2
          use_final_do: True
          final_do_val: 0.15
          relu: 'normal'
          verbose: False
        classifier_params:
          out_channels: 3
    loss:
      name: CrossEntropyLoss
    optimizer:
      name: Adam
      config: 
        lr: 0.001
    scheduler:
      name: OneCycleLR
      config:
        max_lr: 0.01
        total_steps: 20450
        div_factor: 20
        final_div_factor: 500
      interval: step
      monitor: valid/Recall
    metrics:
      - name: Accuracy
        config:
          average: macro
          task: multiclass
          num_classes: 3
          multidim_average: global
      - name: Precision
        config:
          average: macro
          task: multiclass
          num_classes: 3
          multidim_average: global
      - name: Recall
        config:
          average: macro
          task: multiclass
          num_classes: 3
          multidim_average: global
      - name: F1 
        config:
          average: macro
          task: multiclass
          num_classes: 3
          multidim_average: global